import './globals.css'
import {ClusterProvider} from '@/components/cluster/cluster-data-access'
import {SolanaProvider} from '@/components/solana/solana-provider'
import {UiLayout} from '@/components/ui/ui-layout'
import {ReactQueryProvider} from './react-query-provider'

export const metadata = {
  title: 'innovatr',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = []

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Suppress hydration warnings from browser extensions
  if (typeof window !== 'undefined') {
    const originalError = console.error;
    console.error = (...args) => {
      if (args[0]?.includes('Extra attributes from the server')) return;
      originalError.call(console, ...args);
    };
  }
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
